#! /bin/sh

case "$OSTYPE" in
darwin8.0)
echo "Compiling for Darwin"
  g++ -pipe -O3 -finline-limit=65000 -fkeep-inline-functions -finline-functions -ffast-math -fomit-frame-pointer -DNDEBUG  -I. -I.. -D_REENTRANT=1 -compatibility_version 1 -current_version 1 -dynamiclib libtrackalloc.cpp -o libtrackalloc.dylib;;
linux-gnu)
  echo "Compiling for Linux"
  g++ -pipe -g  -I. -I.. -D_REENTRANT=1 -shared -ldl libtrackalloc.cpp -o libtrackalloc.so;;
#  g++ -pipe -march=pentiumpro -O3 -finline-limit=65000 -fkeep-inline-functions -finline-functions -ffast-math -fomit-frame-pointer -DNDEBUG  -I.  -D_REENTRANT=1 -shared libtrackalloc.cpp -o libtrackalloc.so;;
solaris)
  echo "Compiling for Solaris"
#  CC -xildoff -native -noex -xipo=2 -xO5 -mt -DNDEBUG -I.  -D_REENTRANT=1 -G -PIC libtrackalloc.cpp -o libtrackalloc.so;;
  g++ -fPIC -O3 -finline-limit=5000 -mcpu=ultrasparc -DNDEBUG  -I. -I..  -D_REENTRANT=1 -shared libtrackalloc.cpp -o libtrackalloc.so;;
#  g++ -fPIC -pipe -O3 -finline-limit=5000 -fkeep-inline-functions -ffast-math -fomit-frame-pointer -DNDEBUG  -I.  -D_REENTRANT=1 -shared libtrackalloc.cpp -o libtrackalloc.so;;
*)
  echo "hmmm"
esac



