#! /bin/sh

case "$OSTYPE" in
darwin8.0)
echo "Compiling for Darwin"
  g++ -pipe -O3 -finline-limit=65000 -fkeep-inline-functions -finline-functions -ffast-math -fomit-frame-pointer -DNDEBUG  -I. -I.. -D_REENTRANT=1 -compatibility_version 1 -current_version 1 -dynamiclib libdetfaults.cpp -o libdetfaults.dylib;;
linux*)
  echo "Compiling for Linux"
  g++ -pipe -g  -I. -I.. -D_REENTRANT=1 -shared libdetfaults.cpp -o libdetfaults.so -ldl;;
#  g++ -pipe -march=pentiumpro -O3 -finline-limit=65000 -fkeep-inline-functions -finline-functions -ffast-math -fomit-frame-pointer -DNDEBUG  -I.  -D_REENTRANT=1 -shared libdetfaults.cpp -o libdetfaults.so;;
solaris)
  echo "Compiling for Solaris"
#  CC -xildoff -native -noex -xipo=2 -xO5 -mt -DNDEBUG -I.  -D_REENTRANT=1 -G -PIC libdetfaults.cpp -o libdetfaults.so;;
  g++ -fPIC -mcpu=ultrasparc -g -I. -I.. -D_REENTRANT=1 -shared libdetfaults.cpp -o libdetfaults.so;;
#  g++ -fPIC -pipe -O3 -finline-limit=5000 -fkeep-inline-functions -ffast-math -fomit-frame-pointer -DNDEBUG  -I.  -D_REENTRANT=1 -shared libdetfaults.cpp -o libdetfaults.so;;
*)
  echo "hmmm"
esac



