#! /bin/sh

case "$OSTYPE" in
darwin8.0)
echo "Compiling for Darwin"
  g++ -pipe -O3 -finline-limit=65000 -fkeep-inline-functions -finline-functions -ffast-math -fomit-frame-pointer -DDIEHARD_REPLICATED=0 -DDIEHARD_MULTITHREADED=1 -DNDEBUG  -I. -D_REENTRANT=1 -compatibility_version 1 -current_version 1 -dynamiclib libdiehard.cpp -o libdiehard.dylib;;
linux-gnu)
  echo "Compiling for Linux"
#  g++ -pipe -fno-inline -g -I. -D_REENTRANT=1 -shared libdiehard.cpp -o libdiehard.so;;
  #g++  -pipe -g -fno-inline -I. -D_REENTRANT=1 -DDIEHARD_REPLICATED=0 -DDIEHARD_MULTITHREADED=0 -shared libdiehard.cpp -o libdiehard.so -ldl
  #g++  -pipe -g -fno-inline -I. -D_REENTRANT=1 -DDIEHARD_REPLICATED=0 -DDIEHARD_MULTITHREADED=0 -DDIEHARD_DIEFAST=1  -shared libdiehard.cpp -o libdiefast.so -ldl;;
  g++  -static -pipe -march=pentiumpro -g -finline-functions -fkeep-inline-functions -finline-limit=256000 -ffast-math -DNDEBUG  -I. -D_REENTRANT=1 -DDIEHARD_REPLICATED=0 -DDIEHARD_MULTITHREADED=0 -DDIEHARD_DIEFAST=1 -DEXTERMINATOR -DCORRECTING_ALLOCATOR -DRMINATOR -shared libdiehard.cpp -o libdiefast.so -ldl
  g++  -static -pipe -march=pentiumpro -g -finline-functions -fkeep-inline-functions -finline-limit=256000 -ffast-math -DNDEBUG  -I. -D_REENTRANT=1 -DDIEHARD_REPLICATED=0 -DDIEHARD_MULTITHREADED=0 -DCORRECTING_ALLOCATOR -DEXTERMINATOR -shared libdiehard.cpp -o libdiehard.so -ldl;;
solaris)
  echo "Compiling for Solaris"
#  CC -xildoff -native -noex -xipo=2 -xO5 -mt -DNDEBUG -I. -D_REENTRANT=1 -G -PIC libdiehard.cpp -o libdiehard.so;;
  g++ -fPIC -O3 -finline-limit=65000 -mcpu=ultrasparc -DNDEBUG  -I. -D_REENTRANT=1 -DDIEHARD_REPLICATED=0 -DDIEHARD_MULTITHREADED=1 -shared libdiehard.cpp -o libdiehard.so
  g++ -fPIC -O3 -finline-limit=65000 -mcpu=ultrasparc -DNDEBUG  -I. -D_REENTRANT=1 -DDIEHARD_REPLICATED=1 -DDIEHARD_MULTITHREADED=1 -shared libdiehard.cpp -o libdiehard_r.so;;
#  g++ -fPIC -pipe -O3 -finline-limit=5000 -fkeep-inline-functions -ffast-math -fomit-frame-pointer -DNDEBUG  -I. -D_REENTRANT=1 -shared libdiehard.cpp -o libdiehard.so;;
*)
  echo "hmmm"
esac



